### ISSUE TITLE
Proposta - Trocar Travis CI por GitHub Actions

### ISSUE THREAD

**Issue by esron** [Sysvale/helpers#44]
Fica aberta a discussão.

Na minha opinião apesar de o Travis funcionar bem o Actions tem mais possibilidades pra evolução.

**Comment by esron** [comment]
O Travis vem me causando dores de cabeça em outros projetos... Em meus repositórios pessoais eu já estou trocando tudo pra actions.

**Comment by geidsonc** [comment]
Done
