### ISSUE TITLE
Criação do guia de contribuição

### ISSUE THREAD

**Issue by esron** [Sysvale/helpers#8]
Criar um guia de contribuição no arquivo CONTRIBUTING.md como no exemplo do seguinte link:

https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by andregce** [comment]
O guia deve ser escrito em português ou inglês?

**Comment by esron** [comment]
@andregce inicialmente pode ser em inglês, no futuro podemos criar um `CONTRIBUTING_pt-BR.mb`

**Comment by andregce** [comment]
Ok, eu escrevo! Mando um draft hoje mais tarde.

**Comment by esron** [comment]
Fechado em #12
